site_name: Camila Coutinho
site_url: https://caamilacgs.github.io
site_author: Camila Coutinho

theme:
    name: minty
    static_templates:
        - 404.html

nav:
  - Home: index.md
  - 'Sobre Mim':
    - 'Sobre Mim': 'about/sobremim.md'
  - Teste: "teste.md"
  - Novo: "http://google.com"